# Generated by Django 4.2.5 on 2023-10-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('attempts', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('H_1', models.CharField(max_length=2)),
                ('H_2', models.CharField(max_length=2)),
                ('H_3', models.CharField(max_length=2)),
                ('H_4', models.CharField(max_length=2)),
                ('end_time', models.TimeField()),
                ('time_taken', models.TimeField()),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
