# Generated by Django 4.2.5 on 2023-10-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='H_1',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='H_2',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='H_3',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='H_4',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='time_taken',
            field=models.TimeField(null=True),
        ),
    ]
