# Generated by Django 4.2.5 on 2023-10-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_score_h_1_alter_score_h_2_alter_score_h_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
