# Generated by Django 4.2.5 on 2023-10-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_score_h1t'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='H2t',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='score',
            name='H3t',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='score',
            name='H4t',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='score',
            name='end_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='start_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='time_taken',
            field=models.TimeField(default=None, null=True),
        ),
    ]
