# Generated by Django 4.2.5 on 2023-10-18 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_score_h2t_score_h3t_score_h4t_alter_score_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='employee_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='score',
            name='marks',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
