# Generated by Django 4.2.5 on 2023-10-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_score_employee_name_alter_score_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time_taken',
            field=models.DurationField(default=None, null=True),
        ),
    ]
